mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),  
    # include() 함수는 다른 URLconf들을 참조할 수 있도록 도와준다
    # Django가 함수 include()를 만나게 되면, URL의 그 시점까지 일치하는 부분을 잘라내고,
    # 남은 문자열 부분을 후속 처리를 위해 include된 URLconf로 전달한다
    path('admin/', admin.site.urls),
]


'''
Django는 URL 패턴을 사용한다
URL 의 일반적인 형식은 /newsarchive/<year>/<month>/
URL로부터 뷰를 얻기 위해, Django는 'URLconfs'라는 것을 사용한다
URLconf는 URL 패턴을 뷰에 연결한다.
'''

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

'''
브라우저에서 "/polls/34" 주소에 접속하면 detail() 함수를 호출하여 URL에 입력한 ID를 출력할 것이다.

1) 사용자가 "/polls/34"를 요청하면, Django는 mysite.urls 파이썬 모듈을 불러오게 된다. (ROOT_URLCONF 설정에 의해 여기 모듈을 바라보도록 지정되어 있음)
2) mysite.urls에서 urlpatterns라는 변수를 찾고, 순서대로 패턴을 따라간다.
'polls/'를 찾은 후엔, 일치하는 텍스트("polls/")를 버리고, 남은 텍스트인 "34/"를 'polls.url' URLconf로 전달하여 남은 처리를 진행한다.
3) 거기에 '<int:question_id>/'와 일치하여, 결과적으로 detail()뷰 함수가 호출된다.
detail(request=<HttpRequest object>, question_id=34)
question_id=34 부분은 <int:question_id>에서 왔다. 
꺾쇠 괄호(<>)를 사용하면 URL의 일부가 "캡쳐"되어 키워드 인수로 view함수에 전송된다.
문자열의 question_id 부분은 일치하는 패턴을 식별하는데 사용할 이름을 정의하고, int 부분은 URL 경로의 이 부분과 일치하는 패턴을 결정하는 변환기이다.
콜론(:)은 컨버터와 패턴 이름을 구분한다.
'''

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# 모델마다 여러 클래스 변수가 있으며,
# 각 클래스 변수는 모델에서 데이터베이스 필드를 나타냅니다.

# 데이터베이스의 각 필드는 Field 클래스의 인스턴스로 표현
# CharField: 문자필드, DateTimeField: 날짜시간 필드, IntegerField: 정수 필드
class Question(models.Model):
    question_text = models.CharField(max_length=200)  # CharField는 max_length를 입력해줘야 한다
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    # ForeignKey로 관계 설정
    # Choice가 하나의 Question에 관계된다
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        # 모델에 __str__() 메소드 추가
        # 1) 대화식 프롬프트에서 객체의 표현을 편하게 보기 위해
        # 2) Django가 자동으로 생성하는 관리 사이트에서도 객체의 표현이 사용되기 때문

mysite/polls/views.py
from django.http import HttpResponse
#from django.template import loader  #django의 템플릿 시스템 (python 로직 코드와 페이지의 디자인 뷰 분리)
from django.shortcuts import get_object_or_404, render  #template loader 대신 render사용
from django.http import Http404

from .models import Question  #Django 자체 데이터베이스 API를 사용하기 위해

# 색인 페이지
# 최근의 질문들을 표시한다.
def index(request):
    '''
    latest_question_list = Question.objects.order_by('-pub_date')[:5]  # 시스템에 저장된 최신 발행일 투표 질문 최소 5개 
    template = loader.get_template('polls/index.html')
    context = {  # 템플릿에서 쓰이는 변수명과 python 객체를 연결하는 사전형 값
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
    '''
    # 위의 코드 개선 => render() 사용
    # 템플릿에 context를 채워넣어 표현한 결과를 HttpResponse 객체와 함께 돌려주는 구문은 자주 쓰는 용법이다
    # 따라서 Django에서는 shortcurts 기능을 제공한다.
    # 아래가 shortcuts 기능으로 다시 작성한 것이다.
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# 세부 페이지
# 질문 내용과 투표할 수 있는 서식을 표시한다
def detail(request, question_id):
    '''
    try:
        question = Question.objects.get(pk=question_id)  # 요청된 질문의 ID가 없을 경우 Http404 예외를 발생시킨다.
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question':question})
    '''
    # 위의 코드 개선 => get_object_or_404()
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question':question})

# 결과 페이지
# 특정 질문에 대한 결과를 표시한다
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

# 투표 기능
# 특정 질문에 대한 특정 선택을 할 수 있는 투표 기능을 제공한다
def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<!-- 
    템플릿 시스템은 변수의 속성에 접근하기 위해 점-탐색(dot-lookup) 문법을 사용한다
    예제의 {{ questio.question_text }} 구문을 보면, Django는 먼저 question 객체에 대한 사전형으로 탐색한다
    탐색에 실패하게 되면 속성값으로 탐색한다. 
    (이 예에서는 속성값에서 탐색이 완료되지만) 만약 속성 탐색에서도 실패한다면 리스트의 인덱스 탐색을 시도한다.

    반복구문해서 메소드 호출이 이어난다. 
    question.choice_set.all은 python에서 question.choice_set.all() 코드로 해석되는데, 
    이때 반환된 Choice 객체의 반복자는 for 구문에서 사용하기 적당하다.
-->

mysite/polls/templates/polls/index.html
<!--
    python코드와 뷰에서 보여지는 페이지 디자인을 분리하기 위해 Django 의 템플릿 시스템을 이용해보자

    프로젝트의 템플릿 설정은 Django가 어떻게 템플릿을 불러오고 렌더링할 것인지 기술한다.
    기본 설정 파일은 APP_DIRS 옵션이 True로 설정된 DjangoTemplates 백엔드를 구성한다.
    그리고 관례에 따라, DjangoTemplates는 각 INSTALL_APPS 디렉토리의 "templates" 하위 디렉토리를 탐색한다.
    polls/index.html
    --->

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!--
                <li><a href="/polls/{{ question.id }}/">{{
                question.question_text }}</a></li>
                -->
            <li><a href="{% url 'polls:detail' question.id %}"> {{
                question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}